[versions]
agp = "8.12.3"
constraintlayoutVersion = "2.1.4"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
activity = "1.11.0"
constraintlayout = "2.2.1"
cardview = "1.0.0"
materialVersion = "1.11.0"
recyclerview = "1.4.0"
firebaseCommon = "22.0.1"
firebaseAuth = "24.0.1"
firebaseFirestore = "26.0.2"
firebaseDatabase = "22.0.1"
volley = "1.2.1"
navigationFragment = "2.9.5"
navigationUi = "2.9.5"

[libraries]
constraintlayout-v214 = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayoutVersion" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
cardview = { group = "androidx.cardview", name = "cardview", version.ref = "cardview" }
material-v1110 = { module = "com.google.android.material:material", version.ref = "materialVersion" }
recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
firebase-common = { group = "com.google.firebase", name = "firebase-common", version.ref = "firebaseCommon" }
firebase-auth = { group = "com.google.firebase", name = "firebase-auth", version.ref = "firebaseAuth" }
firebase-firestore = { group = "com.google.firebase", name = "firebase-firestore", version.ref = "firebaseFirestore" }
firebase-database = { group = "com.google.firebase", name = "firebase-database", version.ref = "firebaseDatabase" }
volley = { group = "com.android.volley", name = "volley", version.ref = "volley" }
navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigationFragment" }
navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "navigationUi" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

